include: package:lint/analysis_options.yaml

# cSpell: disable
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# analyzer:
#   plugins:

dart_code_metrics:
  extends:
    - recommended
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  rules:
    avoid-nullable-interpolation: false
    unnecessary-trailing-comma: false
    no-empty-block: false
    prefer-match-file-name: false
    avoid-renaming-representation-getters: false
    prefer-correct-callback-field-name: false
    prefer-single-widget-per-file: false

linter:
  rules:
    always_use_package_imports: false
    file_names: false
