include: 
    - package:flutter_lints/flutter.yaml

# cSpell: disable
# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# analyzer:
#   plugins:

formatter:
  page_width: 120

linter:
  rules:
    file_names: false

dart_code_metrics:
  extends:
    # - recommended
    - package:dart_code_metrics_presets/all.yaml
  rules:    
    avoid-nullable-interpolation: false
    avoid-shadowing: false
    member-ordering: false
    newline-before-return: false
    no-empty-block: false
    no-magic-number: false
    prefer-conditional-expressions: false
    prefer-correct-callback-field-name: false
    prefer-match-file-name: false
    avoid-top-level-members-in-tests: false
    prefer-single-widget-per-file: false
    avoid-unnecessary-reassignment: false
    unnecessary-trailing-comma: false